### ISSUE TITLE
Only leave necessary parameters in publishing workflows

### ISSUE THREAD

**Issue by potiuk** [apache/airflow-publish#8]
I think almost all parameters when you trigger the workflows should not be configurable when you run the workflow. I think only "mode" is something that I can imagine release manager should configure.

Also that parameter could be "choice" - and allow to select from available options (VERIFY/RELEASE)

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow

**Comment by potiuk** [comment]
cc: @gopidesupavan

**Comment by gopidesupavan** [comment]
> cc: @gopidesupavan

yeah just seen pushing from other PR :)
